### ISSUE TITLE
Input smaller than output, doing straight copy

### ISSUE THREAD

**Issue by Drjacky** [jishanshaikh4/shrinkpdf#4]
```bash
shrinkpdf.sh: line 59: [: missing `]'
shrinkpdf.sh: line 59: [!: command not found
Input smaller than output, doing straight copy
```

**Comment by jishanshaikh4** [comment]
Thanks for the info, really appreciated. Fixed by #5.

**Comment by Drjacky** [comment]
But still, I get `Input smaller than output, doing straight cop` error and the output is as the same size as the input.

**Comment by jishanshaikh4** [comment]
This might mean that the output is no longer compressible by Ghostscript. Can you share me any document (PDF) you are trying? You sure, you are on bash terminal with Ghostscript (gs) installed?

**Comment by jishanshaikh4** [comment]
Also, the default resolution for compression is 72 dpi (and the PDF may have lower resolution), you can manually specify for the resolution as an integer value in the third parameter.

**Comment by Drjacky** [comment]
Yes, I'm in bash-5 and gs is installed already: `Warning: ghostscript 9.55.0 is already installed and up-to-date.`

**Comment by Drjacky** [comment]
But, by a low number for the quality (third param), it works.

**Comment by jishanshaikh4** [comment]
> But, by a low number for the quality (third param), it works.

Yes, it should be explicitly mentioned in the README.
